### ISSUE TITLE
希望能将项目打包上传到pypi

### ISSUE THREAD

**Issue by Soulter** [Lxns-Network/nakuru-project#14]
用pip git来安装在国内会比较麻烦，如果能上传到pypi就好了

**Comment by JoinChang** [comment]
收到，过段时间会上

**Comment by JoinChang** [comment]
感谢贡献，已经将项目上传至 PyPI，详见：https://pypi.org/manage/project/nakuru-project/releases/

README.md 也已修改 pip 的安装命令：https://github.com/Lxns-Network/nakuru-project/commit/59f5c1bf898adf8773b2a22139a00df79a6334de
