### ISSUE TITLE
请问一下如何实现定时发送消息呢？

### ISSUE THREAD

**Issue by Find-fengqingwu** [Lxns-Network/nakuru-project#22]
请问一下有类似[GraiaScheduler](https://scheduler.api.graia.cn/)或者`@channel.use(SchedulerSchema(crontabify("0 12 * * *")))`的方式实现定时发送消息吗？还是说有别的实现方式？

**Comment by JoinChang** [comment]
这个功能不支持，得自己实现呢，不好意思
