### ISSUE TITLE
不支持连接配有access token的服务端

### ISSUE THREAD

**Issue by moozae** [Lxns-Network/nakuru-project#9]
https://github.com/botuniverse/onebot-11/blob/master/communication/authorization.md
onebot协议中支持配置access token以防止api被滥用，但是nakuru-project并不支持连接配有access token的onebot服务端

**Comment by moozae** [comment]
得，解决了（x
顺便水了个pr #10

**Comment by JoinChang** [comment]
不好意思，没收到通知邮件。

看了一下，pr里没有处理token为空的情况，token的默认值建议设为None。在protocol中，access_token可以使用params参数发送。修改后可以commit上来，我再合并。

fetch那块确实很屎，但我也不太清楚该怎么优化（

**Comment by moozae** [comment]
做过测试token为空的时候直接发送不会有任何问题x

**Comment by moozae** [comment]
所以当时我就没有加判断

**Comment by moozae** [comment]
token为空的情况我做过测试，不做任何处理并不会遇到任何问题，所以当时就没有加token判断想x

**Comment by JoinChang** [comment]
虽然不会出问题，但还是不太优雅
